name: Infrastructure Deployment
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Pulumi
        uses: pulumi/actions@v3
        with:
          command: stack init test
          stack-name: test
          work-dir: ./infrastructure/pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          
      - name: Deploy Infrastructure
        uses: pulumi/actions@v3
        with:
          command: ${{ github.event_name == 'pull_request' && 'preview' || 'up' }}
          stack-name: test
          work-dir: ./infrastructure/pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}



